# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-11 13:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/jpg', verbose_name='Картинка')),
                ('text', models.TextField(blank=True, verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'Каталог',
                'verbose_name_plural': 'Каталог',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Заголовок')),
                ('icon', models.ImageField(upload_to='images/png', verbose_name='Картинка')),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Filter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Заголовок')),
                ('slug', models.SlugField(unique=True, verbose_name='Слаг')),
            ],
            options={
                'verbose_name': 'Фильтр',
                'verbose_name_plural': 'Фильтры',
            },
        ),
        migrations.CreateModel(
            name='Style',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Заголовок')),
            ],
            options={
                'verbose_name': 'Стиль',
                'verbose_name_plural': 'Стили',
            },
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(upload_to='images/jpg', verbose_name='Картинка')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Слаг')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='works.Category', verbose_name='Категория')),
                ('filter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='works.Filter', verbose_name='Фильтр')),
                ('style', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='works.Style', verbose_name='Стиль')),
            ],
            options={
                'verbose_name': 'Робота',
                'verbose_name_plural': 'Работы',
            },
        ),
        migrations.AddField(
            model_name='catalog',
            name='filter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='works.Filter', verbose_name='Фильтр'),
        ),
    ]
